### ISSUE TITLE
p:variable in atomic steps

### ISSUE THREAD

**Issue by xquery** [xproc/1.0-specification#132]
as per action A-260-02;

original proposal 
https://lists.w3.org/Archives/Public/public-xml-processing-model-wg/2014Dec/0010.html

latest discussion in Dec 15 2014 meeting minutes
https://lists.w3.org/Archives/Public/public-xml-processing-model-wg/2014Dec/0015.html

TBD- will synthesise

**Comment by ndw** [comment]
p:variable is allowed in atomic steps
The scope rules remain the same, not available for shorthand options on the parent

**Comment by xquery** [comment]
discussion to allow p:variable everywhere, probably means its moot doing this

**Comment by ndw** [comment]
I believe this issue has been overtaken by the variable scoping changes.
