### ISSUE TITLE
shouldn't variable connections also be listed in "2.5 Connections" ?

### ISSUE THREAD

**Issue by rdeltour** [xproc/1.0-specification#141]
Section 2.5 [Connections](https://xproc.github.io/specification/langspec/xproc20/head/xproc20/#connections) says:

> output ports are connected when they are referenced by another input port, declared output or other expression and may be connected to:
> - The input port of some other step (including p:iteration-source or p:viewport-source).
> - The p:xpath-context of a p:choose or p:when.
> - An option assigned with p:with-option.
> - One of the outputs declared on its container.

An output port can also be referenced in the connections of a `p:variable`. Shouldn't that make the port "connected" too ?

**Comment by alexmilowski** [comment]
Yes, this is the same situation as p:option

**Comment by ndw** [comment]
Yes. Fixed.
