### ISSUE TITLE
declare the content type of an inline document

### ISSUE THREAD

**Issue by rdeltour** [xproc/1.0-specification#144]
In the current draft, the [`p:inline` element](https://xproc.github.io/specification/langspec/xproc20/head/xproc20/#p.inline) has no `content-type` attribute, is it intentional ?

**Comment by ndw** [comment]
Per http://www.w3.org/XML/XProc/2015/03/11-minutes.html this is a question of making it possible to have p:inline contain non-XML documents. That's also something to be spec'd.

**Comment by ndw** [comment]
Add content-type and encoding attributes to p:inline; if encoding="base64" then decode the base64 encoded text to get the content. text/\* and application/xml and application/xml+\* all do the obvious thing
