### ISSUE TITLE
declare the content type of a document loaded with p:load

### ISSUE THREAD

**Issue by rdeltour** [xproc/1.0-specification#145]
In the current draft, the [`p:load` step](https://xproc.github.io/specification/langspec/xproc20/head/xproc20-steps/#c.load) has no `content-type` option, is it intentional ?

**Comment by ndw** [comment]
No, I think that's an oversight.

**Comment by ndw** [comment]
Per http://www.w3.org/XML/XProc/2015/03/11-minutes.html this is really a question of making the p:load step able to load non-XML documents.

**Comment by ndw** [comment]
Resolved by recent drafts, I believe.
