### ISSUE TITLE
p:assert use case

### ISSUE THREAD

**Issue by xquery** [xproc/1.0-specification#158]
as per ACTION A-269-03, investigate if p:assert would be useful.

Some questions that immediately come to mind;
- global enable/disable ?
- integration with logging ?
- relation to p:validate ?
- relation to cx:depends-on ?

will draft a message for broader review.

**Comment by rdeltour** [comment]
In case it might help, here's the [`px:assert` step](https://github.com/daisy/pipeline-modules-common/blob/master/common-utils/src/main/resources/xml/xproc/assert.xpl) we have in our utils library, courtesy of @josteinaj.

**Comment by xquery** [comment]
yes it does help, will be sending out email to list for comment soonish.

**Comment by josteinaj** [comment]
> global enable/disable ?

I don't see the use-case for a global disable. Assertions are much like validations; it would be kind of like having a global disable for validations. When I use assertions (with our `px:assert` step) it's intended to be run in production, not just during development. A couple of things that we use `px:assert` for is
- to make sure that there's a certain number of documents in a sequence; usually 1 (which makes me think that maybe `max` and `min` attributes on p:input/p:output in step declarations would be useful?), and
- to check the syntax of option values (which makes me think that maybe a `pattern` attribute on p:option similar to the one on HTML input elements would be useful?).

> integration with logging ?

That would be useful. Assertions does not need to be fatal. Our `px:assert` works like a `p:identity` when there's no error code specified, in which case the assertion will just show a warning if it fails. If the logging mechanism supports severity levels, the log message would by default have a warning-severity.

> relation to p:validate ?

In a way, p:assert would just be a very simplified p:validate I suppose. Could warnings and errors from `p:validate` also be logged?

> relation to cx:depends-on ?

If `p:assert` works like a `p:identity` then the default connection will create the needed dependencies in most situations, and if `depends-on` is standardized in 2.0 then that will take care of the rest I think?

**Comment by xquery** [comment]
after further cogitation and discussion (thx to everyone for the valuable feedback) I am going to close this bug on the grounds that we believe proposed enhancements elsewhere (ex. depends-on) addresses emulating this behavior in v2.

**Comment by josteinaj** [comment]
I'm curious what other enhancements makes `p:assert` unneccessary? `depends-on` is not really related to `p:assert` as I see it. From [the minutes](http://www.w3.org/2015/04/08-xproc-minutes.html) it seems that `p:error` is intended to fill the role of `p:assert`?

**Comment by xquery** [comment]
yes, you are right ... once we generate words in the relevant part of the spec things should be clear; I guess what I am saying is that we think we already have planned changes that minimally address this use case though clearly we are not adding a p:assert to the language.

We will raise a more generalised issue for tracking this so if it is ok with you I will keep this bug closed.
