### ISSUE TITLE
consider expand-text on p:declare-step

### ISSUE THREAD

**Issue by xquery** [xproc/1.0-specification#167]
In xslt, you can define expand-text at top level xsl:stylesheet and then you can selectively override behavior; wondering if we need to consider something similar with p:declare-step. 

And it follows that we would need to define how overrides of expand-text works.

**Comment by ndw** [comment]
Probably needs to be allowed on any compound step.

**Comment by ndw** [comment]
Also: make explicit that if unspecified the value of expand-text is false.

**Comment by ndw** [comment]
The XSLT definition of expand-text doesn't require a default, it's worded as "above you"

**Comment by ndw** [comment]
From 10 June f2f: the context node is the default readable port for the step in which the p:inline occurs. AVTs are only on "shortcut" option values.

**Comment by ndw** [comment]
The spec needs to specify which variable bindings are in scope.

**Comment by ndw** [comment]
In an effort to avoid the question of having to enable TVTs, let's get rid of expand-text and just say that curly braces are TVTs in p:inline; if you don't like that, double them up.

**Comment by ndw** [comment]
Make sure the spec specifies the context node and more fully how expansion is performed (atomization, etc.)

**Comment by ndw** [comment]
New thinking:
expand-text is true by default and can only occur on p:inline
TVTs are not atomized, they copy content.
