### ISSUE TITLE
The p:xslt step should explicitly mention that the order of the  secondary sequence is implementation defined

### ISSUE THREAD

**Issue by rdeltour** [xproc/1.0-specification#17]
## Proposal

in [7.1.31 p:xslt](http://www.w3.org/TR/xproc/#c.xslt) right after

> All other result documents appear on the secondary port.

add the sentence:

> The order in which result documents are produced on the secondary port is _implementation defined_
## Rationale

XSLT 2 0 defines the output of a transform as a **set** of final result trees. XProc's sequences of documents being ordered, it is easy to be confused and take for granted that e.g.  the following pipeline:

``` xml
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc" version="1.0">
    <p:output port="result" sequence="true">
        <p:pipe port="secondary" step="iterator"/>
    </p:output>
    <p:xslt name="iterator" template-name="do">
        <p:input port="source">
            <p:empty/>
        </p:input>
        <p:input port="stylesheet">
            <p:inline>
                <xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
                    <xsl:template name="do">
                        <xsl:for-each select="1 to 10">
                            <xsl:result-document href="{concat('doc-',position())}">
                                <doc>
                                    <xsl:value-of select="position()"/>
                                </doc>
                            </xsl:result-document>
                        </xsl:for-each>
                    </xsl:template>
                </xsl:stylesheet>
            </p:inline>
        </p:input>
        <p:input port="parameters">
            <p:empty/>
        </p:input>
    </p:xslt>
    <p:sink/>
</p:declare-step>
```

Produces documents on its `result` output port  "in order" (from 1 to 10).

The confusion is somewhat reinforced by the default behavior of Calabash with Saxon HE and PE, which does produce secondary result ports synchronously (i.e. in XSLT's processing order).

However, nothing guarantees the order in which documents appear in the `secondary` port, neither from XSLT 2.0 nor XProc 1.0. The spec should be explicit about that to reduce the risk of misinterpretation.

**Comment by josteinaj** [comment]
Should there then be a sorting mechanism built into `p:xslt`? Or some kind of `p:sort` step to sort a sequence? Or a `sort` attribute on `p:pipe`?

**Comment by rdeltour** [comment]
> Should there then be a sorting mechanism built into p:xslt

Contrary to what I originally believed, there is absolutely no guarantee in XSLT 2.0 (nor 3.0 FWIW) that  any order is respected. This is entirely implementation defined.
In the example above, an implementation is **not** required to provide a _synchronous_ mode where the result documents are produced in the same order as the processing the sorting sequence.

Since a sorting mechanism cannot be built-in to `p:xslt` _silently_, i.e. requires user setting of a comparison key, I think the best solution is to use a dedicated sorting step.

>  Or some kind of p:sort step to sort a sequence

Yep, :+1: to add something like that to the [v2 standard steps](http://www.w3.org/TR/xproc-v2-req/#more-steps)

**Comment by xquery** [comment]
Thx Romain / Jostein, 

when we were gathering up requirements for v2

http://www.w3.org/wiki/XProc_New_Steps 

we briefly discussed the idea of a p:sort step, something which would be trivial to implement in xproc itself.

Our v2 req doc

http://www.w3.org/TR/xproc-v2-req/ 

currently makes no mention of ordering.

I think the design decision is about implementing something like this as a 'step' vs 'some primitive built' , we probably want to discuss this first before we start clarifying specific step behaviour.

**Comment by rdeltour** [comment]
Thanks for the info Jim!

FYI to give you some background, I was hit by that misinterpretation in the following scenario: in our HTML to EPUB 3 conversion, we split a single HTML source into multiple HTML docs using XSLT secondary result documents. We assumed  the `secondary` sequence was in the original document order and used it as-is to compute the EPUB spine (which determines the reading order).

Out of curiosity I looked at @gimsieke's "transpect" project and it seems they were affected too (they followed a similar approach).

Well, it makes only two of us, but I believe it shows the confusion is easy, hence the proposal to make it explicit in the spec :wink:

**Comment by xquery** [comment]
so, shooting from the hip

```
<p:sort order-by="(ascending|descending|document-order|numeric)" select=""/>
```

not so sure about overloading select here.

and we would need to think more about finer points like case sensitivity or how far we would go with collation sort order (w/ xproc defining Unicode code point collation by default)

**Comment by josteinaj** [comment]
`p:sort` could also be modelled after, and behave exactly like, `xsl:sort`. For instance:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<p:declare-step type="p:sort" xmlns:p="http://www.w3.org/ns/xproc">
    <p:input port="source" sequence="true"/>
    <p:output port="result" sequence="true"/>
    <p:option name="select"/> <!-- expression -->
    <p:option name="lang"/> <!-- { nmtoken } -->
    <p:option name="order"/> <!-- { "ascending" | "descending" } -->
    <p:option name="collation"/> <!-- { uri } -->
    <p:option name="stable"/> <!-- { "yes" | "no" } -->
    <p:option name="case-order"/> <!-- { "upper-first" | "lower-first" } -->
    <p:option name="data-type"/> <!-- { "text" | "number" | qname-but-not-ncname }> -->
</p:declare-step>
```

And a demo implementation which wraps `xsl:sort`:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<p:declare-step type="px:sort" name="main" xmlns:p="http://www.w3.org/ns/xproc" xmlns:c="http://www.w3.org/ns/xproc-step" xmlns:px="http://www.example.net/" version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

    <p:input port="source" sequence="true"/>
    <p:output port="result" sequence="true"/>

    <p:option name="select"/> <!-- expression -->
    <p:option name="lang"/> <!-- { nmtoken } -->
    <p:option name="order"/> <!-- { "ascending" | "descending" } -->
    <p:option name="collation"/> <!-- { uri } -->
    <p:option name="stable"/> <!-- { "yes" | "no" } -->
    <p:option name="case-order"/> <!-- { "upper-first" | "lower-first" } -->
    <p:option name="data-type"/> <!-- { "text" | "number" | qname-but-not-ncname }> -->

    <p:in-scope-names name="attributes"/>

    <p:count>
        <p:input port="source">
            <p:pipe port="source" step="main"/>
        </p:input>
    </p:count>
    <p:choose>
        <p:when test=".=0">
            <p:identity>
                <p:input port="source">
                    <p:empty/>
                </p:input>
            </p:identity>
        </p:when>
        <p:otherwise>
            <p:xslt>
                <p:input port="source">
                    <p:inline>
                        <xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:c="http://www.w3.org/ns/xproc-step" version="2.0" exclude-result-prefixes="#all">
                            <xsl:template match="/*">
                                <c:result>
                                    <xsl:for-each select="collection()">
                                        <xsl:sort/>
                                        <xsl:copy-of select="."/>
                                    </xsl:for-each>
                                </c:result>
                            </xsl:template>
                        </xsl:stylesheet>
                    </p:inline>
                    <p:pipe port="result" step="attributes"/>
                </p:input>
                <p:input port="parameters">
                    <p:empty/>
                </p:input>
                <p:input port="stylesheet">
                    <p:inline>
                        <xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:c="http://www.w3.org/ns/xproc-step" version="2.0" exclude-result-prefixes="#all">
                            <xsl:template match="@*|node()">
                                <xsl:copy>
                                    <xsl:apply-templates select="@*|node()"/>
                                </xsl:copy>
                            </xsl:template>
                            <xsl:template match="xsl:sort">
                                <xsl:copy>
                                    <xsl:for-each select="collection()/c:param[@value]">
                                        <xsl:attribute name="{@name}" select="@value"/>
                                    </xsl:for-each>
                                </xsl:copy>
                            </xsl:template>
                        </xsl:stylesheet>
                    </p:inline>
                </p:input>
            </p:xslt>
            <p:identity name="xslt"/>

            <p:xslt>
                <p:input port="source">
                    <p:pipe port="source" step="main"/>
                </p:input>
                <p:input port="parameters">
                    <p:empty/>
                </p:input>
                <p:input port="stylesheet">
                    <p:pipe port="result" step="xslt"/>
                </p:input>
            </p:xslt>
            <p:for-each>
                <p:iteration-source select="/*/*"/>
                <!-- remove xmlns:c -->
                <p:xslt>
                    <p:input port="parameters">
                        <p:empty/>
                    </p:input>
                    <p:input port="stylesheet">
                        <p:inline>
                            <xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:c="http://www.w3.org/ns/xproc-step" version="2.0" exclude-result-prefixes="#all">
                                <xsl:template match="@*|node()">
                                    <xsl:copy>
                                        <xsl:apply-templates select="@*|node()"/>
                                    </xsl:copy>
                                </xsl:template>
                            </xsl:stylesheet>
                        </p:inline>
                    </p:input>
                </p:xslt>
            </p:for-each>
        </p:otherwise>
    </p:choose>

</p:declare-step>
```

**Comment by xquery** [comment]
yes that looks right ... will discuss with the chair if we can put this on the agenda for next week

note- we are still working out the workflow for speccing out new steps, currently we envisage proposals to come into the xproc/steps repo ... once we've got that ironed out I will  use p:sort as as the first 'customer'.

**Comment by ndw** [comment]
Given an XProc implementation of p:sort, I'd be curious to know if it effectively solves the problem. Is that something you could try, @rdeltour

**Comment by rdeltour** [comment]
I've not tried it _yet_, but I'm pretty sure that @josteinaj's implem would solve our particular use case: we use a specific naming scheme for docs base URIs, so we can safely use them as keys.

**Comment by ndw** [comment]
I've added a p:sort step to the extensions repo and added the proposed text to the specification, I think this issue is closed. Reopen if you disagree.

**Comment by rdeltour** [comment]
:+1:  thx !
