### ISSUE TITLE
Bind variables from a map

### ISSUE THREAD

**Issue by htInEdin** [xproc/1.0-specification#180]
With the advent of TVTs everywhere, p:template has value only because it has a parameters attributed, i.e. it allows you to compute the bindings of 'variables' that will be interpolated into the template.

If we had a `<p:variables select="[a map]"/>` which bound all the keys to their values as variables in the XProc context, we wouldn't need it at all.  And I think we'll want that for other things.

**Comment by vojtechtoman** [comment]
Note the `p:in-scope-names` step. Could a similar XPath function exist that would, for instance, expose all in-scope options/variables as a map?

**Comment by htInEdin** [comment]
I realise what I wrote was ambiguous -- what I meant was a step that moves a map into variables, not the other way

**Comment by ndw** [comment]
I don't understand what `p:variables` would do.

**Comment by htInEdin** [comment]
In brief, if variable `mm' was bound to`{"e" -> 2.71, "pi" -> 3.14}', then (given our decision to allow `p:variable' at the top-level)

```
<p:variables select="$mm"/>
```

would have the same effect as

```
<p:variable name="e" value="2.71"/>
<p:variable name="pi" value="3.14"/>
```

Once we've done that, then

```
<p:template parameters="$mm"/>
 <p:inline port="template">
  <circumference>2*{$pi}*{/circle/@radius}</circumference>
 </p:inline>
</p:template>
```

could be replaced with

```
<p:variables select="$mm"/>
<p:variable name="radius" select="/circle/@radius"/>
<p:identity>
 <circumference>2*{$pi}*{$radius}</circumference>
</p:identity>
```

[Stop reading here if you are already uninterested.]

I don't like needing the extra variable.  Maybe there's a way to fix that.
The following is too ugly:

```
<p:variables select="$mm"/>
 <p:group>
  <p:output name="result">
   <circumference>2*{$pi}*{/circle/@radius}</circumference>
  </p:output>
 </p:group>
```

(supposing an empty subpipeline is allowed)

**Comment by ndw** [comment]
I don't think p:variables can work the way you've spec'd it.

Consider:

```
<p:pipeline>
  <p:option name="mm" as="map:map"/>

  <p:variables select="$mm"/>

  <p:some-step opt="$value"/>
```

Because the variable name binding is dynamic, there's no way to determine statically whether or not the variable $value will be in scope. And there's no way to know if there's a dependency edge between the p:variables "step" and the "some-step" step.

I suppose we could postpone the variable analysis to runtime and say that all steps depend on any p:variables that precede them in scope, but ... urgh.

I'd rather keep variable scoping lexical and static.

**Comment by ndw** [comment]
At the 8 July 2015 meeting, we proposed to close this. Henry, if you want it reconsidered, please reopen it.
