### ISSUE TITLE
2.6 Allow attribute value templates

### ISSUE THREAD

**Issue by ndw** [xproc/1.0-specification#33]
The syntactic sugar that allows step options to be expressed concisely as attribute values on a step is foiled whenever the value of the option must be computed by the pipeline. Allowing those options to contain XSLT-style attribute value templates (AVTs) would simplify many pipelines. Additionally, allowing AVTs in other places, such as the href attribute on p:document, will be considered.

[XSLT 3.0] introduces a feature which allows expressions in curly braces to be evaluated in element content. This feature is similar to the facility provided by the p:template step. Extending XProc to support curly braces in a manner consistent with [XSLT 3.0] will be considered.

**Comment by innovimax** [comment]
Do we want to allow curly braces or add "_att" to allow such behaviour (as it's done in XSLT 3.0 ) ?

**Comment by ndw** [comment]
I think we might want to do both. Allowing, for example, href on p:store to be an AVT would make it possible to write

```
  <p:store href="{$expression}"/>
```

which would set the value of the href attribute based on a runtime evaluation of `$expression` (and would have, for example, the default readable port (I assume) as its context).

We could also allow _href with the proviso that it must be evaluated statically.

The much more interesting question is, should we allow _step or _port on p:pipe? This would allow a static parameter to have influence over the connections in the pipeline. Not impossible.

I'll start a new issue for this.

**Comment by ndw** [comment]
c.f. issue #78

**Comment by ndw** [comment]
This issue was addressed by build 97 on 29 October 2014.
