### ISSUE TITLE
2.7.4 Syntax: allow <p:input port="portname"/>

### ISSUE THREAD

**Issue by ndw** [xproc/1.0-specification#37]
XProc 1.0 offers relatively few default behaviors, requiring instead that pipelines specify every construct fully. User experience has demonstrated that this leads to very verbose pipelines and has been a constant source of complaint. XProc 2.0 will introduce a variety of syntactic simplifications as an aid to readability and usability, including but not limited to:

`<p:input port="portname"/>` is a shortcut for a nested p:empty.

**Comment by xquery** [comment]
Currently we throw a static error (err:XS0032) if no default readable port can be connected when using p:input with just a port attribute. 

Satisfying this requirement means that we now infer a p:empty instead of throwing the error which introduces hard to debug problems as we are silent about no documents flowing to the port. In many instances this may not be a problem as one would recognise nothing is flowing through and adjust accordingly, in more complicated pipelines it may not be readily apparent that this is the case.

Conversely, I assume this default behaviour is being proposed because its hard for end users to grok undefined default readable port errors ... hmmm .... I think this needs (re) clarification; maybe the discussion was had already and the trade offs were acceptable.

**Comment by innovimax** [comment]
I agree with Jim here
I think that we will need to consider a matrix of weight (what we win versus what we loose by removing those few strokes here and there)
It seems to me that this issue may end up being drop because the net win may not be worth

**Comment by ndw** [comment]
Perhaps. It could be argued that consistent with making p:inline optional, en empty p:input is just a binding to p:empty. I'm not asserting that I'm making that argument, I'm just saying...

**Comment by innovimax** [comment]
Indeed at least those two can give a consistent story. Thanks for the clarification

**Comment by vojtechtoman** [comment]
To be honest, I am not conmfortable with this. In my view, a `port` attribute on a `p:input` connection will be confusing with input declarations.

As others have pointed out already, implying `p:empty` will not work without changing the behavior with regard to the default readable port. Personally, I don't think this is worth the effort.

But apparently Norm had a different behavior in mind (based on his recent - removed? - comment), which is to connect (but connect what??) to the output port `port` of the step that supplies the default readable port. Regarding this, note that we already have #35 and #34 that aim to support this on the `p:pipe` level which I think is a better place for such things.

On the other hand, we also have #36 that feels like a good idea to me. So I am kind of torn with these things. It has probably something to do with the 'static-ness' of these enhancements: `<p:input port="name" href="..."/>` would work perfectly fine in a port declaration (nothing confusing here), whereas `<p:input port="..."/>` is a completely dynamic thing - and it also immediately clashes with the input port declaration syntax.

**Comment by josteinaj** [comment]
> But apparently Norm had a different behavior in mind (based on his recent - removed? - comment), which is to connect (but connect what??) to the output port port of the step that supplies the default readable port.

I think it would be useful to be able to do this on the `p:input` level. How about a "pipe" attribute (or similar):

``` xml
<px:my-custom-step/>
<p:xslt>
    <p:input port="stylesheet" pipe="stylesheet"/>
</p:xslt>
```

...this would pipe the "stylesheet" port of px:my-custom-step into the stylesheet port of p:xslt.

It's common that you have to pipe a secondary port from the previous step into a step, so this could save many lines of code.

**Comment by vojtechtoman** [comment]
A `pipe` attribute actually looks better to me (so maybe my problem is really a naming problem). If we go that route, we could even consider supporting 'fully-qualified' port references:

``` xml
<px:my-custom-step name="my-step">
  ...
</px:my-custom-step>
...
<p:xslt>
  <p:input port="stylesheet" pipe="my-step/stylesheet"/>
</p:xslt>
```

(Note that port names are NCNames.)

**Comment by ndw** [comment]
My deleted comment was a total brain cramp on my part. I was thinking of p:pipe, not p:input.

**Comment by ndw** [comment]
The pipe idea probably belongs in issue #36.

**Comment by ndw** [comment]
The WG elected not to pursue this proposal at the 8 Oct 2014 meeting.
