### ISSUE TITLE
2.7.9 Syntax: consider harmonizing p:viewport-source and p:iteration-source

### ISSUE THREAD

**Issue by ndw** [xproc/1.0-specification#42]
XProc 1.0 offers relatively few default behaviors, requiring instead that pipelines specify every construct fully. User experience has demonstrated that this leads to very verbose pipelines and has been a constant source of complaint. XProc 2.0 will introduce a variety of syntactic simplifications as an aid to readability and usability, including but not limited to:

Consider harmonizing p:viewport-source and p:iteration-source

**Comment by xquery** [comment]
to avoid duplicate working ... this is a heads up that I am taking a stab at this issue.

**Comment by ndw** [comment]
Fixed in the 10 June 2015 draft.
