### ISSUE TITLE
3.6 Enhance try/catch

### ISSUE THREAD

**Issue by ndw** [xproc/1.0-specification#50]
Support for catching errors in XProc 1.0 is limited to a simple p:try/p:catch pair, which catches and handles all errors uniformly. To align XProc with modern languages, the try/catch mechanism will be extended to support the ability to catch specific errors and possibly with the addition of a “finally” construct.

**Comment by xquery** [comment]
thread discussing multiple catch 

http://lists.w3.org/Archives/Public/xproc-dev/2013Aug/0000.html
